# Generated by Django 3.2.9 on 2021-12-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('titre', models.CharField(max_length=128)),
                ('chapter', models.CharField(max_length=32)),
                ('partie', models.IntegerField()),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Texts',
        ),
    ]
