# Generated by Django 3.2.9 on 2021-12-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_auto_20211211_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='chapter',
            field=models.IntegerField(),
        ),
    ]
