# Generated by Django 3.2.9 on 2021-12-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_alter_text_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=128)),
                ('tumbnail', models.ImageField(blank=True, null=True, upload_to='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(),
        ),
    ]
