# Generated by Django 4.0 on 2021-12-18 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_alter_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mouvement',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='resume',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
