# Generated by Django 4.0 on 2021-12-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0006_book_mouvement_book_resume_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='resume',
            field=models.TextField(blank=True),
        ),
    ]
