# Generated by Django 4.0 on 2021-12-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0009_alter_book_mouvement_alter_book_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='titre',
        ),
        migrations.AddField(
            model_name='book',
            name='slug_title',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='text',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='texts.book'),
        ),
        migrations.AddField(
            model_name='text',
            name='slug_name',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
