# Generated by Django 4.0 on 2021-12-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0012_rename_tumbnail_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='text_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
