# Generated by Django 4.0 on 2021-12-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0014_sequences_book_sequence_text_sequence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sequences',
            new_name='Sequence',
        ),
    ]
