# Generated by Django 4.0 on 2021-12-21 20:42

from django.db import migrations, models
import texts.models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0015_rename_sequences_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug_title',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='slug_name',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=texts.models.SeparatedValuesField(separator='<br>'),
        ),
    ]
