# Generated by Django 4.0 on 2021-12-22 20:39

from django.db import migrations, models
import django.db.models.deletion
import texts.models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0016_alter_book_slug_title_alter_text_slug_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrait', models.CharField(max_length=512)),
                ('line', texts.models.SeparatedValuesField()),
                ('outil', models.CharField(max_length=128)),
                ('outil_type', models.IntegerField(choices=[(1, 'figure de style'), (2, 'champs lexical'), (3, 'poctuation'), (4, 'temps'), (5, 'tonalités'), (6, 'autre')])),
                ('interpretation', models.TextField()),
                ('Text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.text')),
            ],
        ),
    ]
