# Generated by Django 4.0 on 2021-12-22 20:50

from django.db import migrations
import texts.models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0017_text_interpretation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_interpretation',
            name='line',
            field=texts.models.SeparatedValuesField(final_type=int),
        ),
    ]
