# Generated by Django 4.0 on 2021-12-23 08:08

from django.db import migrations, models
import django.db.models.deletion
import texts.models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0018_alter_text_interpretation_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_interpretation',
            name='extrait',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='text_interpretation',
            name='interpretation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='text_interpretation',
            name='line',
            field=texts.models.SeparatedValuesField(blank=True, final_type=int),
        ),
        migrations.AlterField(
            model_name='text_interpretation',
            name='outil',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='text_interpretation',
            name='outil_type',
            field=models.IntegerField(blank=True, choices=[(1, 'figure de style'), (2, 'champs lexical'), (3, 'poctuation'), (4, 'temps'), (5, 'tonalités'), (6, 'autre')]),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('conclusion', models.TextField()),
                ('ouverture', models.TextField()),
                ('partie_I', models.CharField(max_length=256)),
                ('partie_II', models.CharField(blank=True, max_length=256)),
                ('partie_III', models.CharField(blank=True, max_length=256)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.text')),
            ],
        ),
    ]
