# Generated by Django 4.0 on 2021-12-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0019_alter_text_interpretation_extrait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='partie_IV',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
