# Generated by Django 4.0 on 2021-12-24 12:44

from django.db import migrations, models
import texts.models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0020_plan_partie_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ligne_partie_I',
            field=texts.models.SeparatedValuesField(blank=True, editable=False, final_type=int),
        ),
        migrations.AddField(
            model_name='plan',
            name='ligne_partie_II',
            field=texts.models.SeparatedValuesField(blank=True, editable=False, final_type=int),
        ),
        migrations.AddField(
            model_name='plan',
            name='ligne_partie_III',
            field=texts.models.SeparatedValuesField(blank=True, editable=False, final_type=int),
        ),
        migrations.AddField(
            model_name='plan',
            name='ligne_partie_IV',
            field=texts.models.SeparatedValuesField(blank=True, editable=False, final_type=int),
        ),
        migrations.AlterField(
            model_name='plan',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ouverture',
            field=models.TextField(blank=True),
        ),
    ]
