# Generated by Django 4.0 on 2021-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0021_plan_ligne_partie_i_plan_ligne_partie_ii_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='ligne_partie_I',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='ligne_partie_II',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='ligne_partie_III',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='ligne_partie_IV',
        ),
        migrations.AddField(
            model_name='plan',
            name='ligne_fin_partie_I',
            field=models.IntegerField(blank=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='ligne_fin_partie_II',
            field=models.IntegerField(blank=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='ligne_fin_partie_III',
            field=models.IntegerField(blank=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='ligne_fin_partie_IV',
            field=models.IntegerField(blank=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text_interpretation',
            name='line',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
