# Generated by Django 4.0 on 2021-12-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0022_remove_plan_ligne_partie_i_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='problematique',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
