# Generated by Django 4.0 on 2021-12-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0023_plan_problematique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='ligne_fin_partie_I',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ligne_fin_partie_II',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ligne_fin_partie_III',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ligne_fin_partie_IV',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
